#Add task to set kubeconfig for EKS Cluster using aws eks update-kubeconfig command
#Deploy ngnix application to EKS Cluster
#Add code to set kubeconfig for EKS Cluster
#use kubeconfig as ~/.kube/config
#Replica count should be 2
#Expose the application on port 80
#Use LoadBalancer service type

- name: Deploy Nginx application to EKS Cluster
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Check Python version
      command: python3 --version
    - name: Set kubeconfig for EKS Cluster
      command: aws eks update-kubeconfig --name jaya20-eks-cluster --region eu-west-1
    - name: Deploy Nginx application to EKS Cluster
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: default
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx
                  ports:
                  - containerPort: 80
        wait: yes
    - name: Expose the application on port 80
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: default
          spec:
            selector:
              app: nginx
            ports:
            - protocol: TCP
              port: 80
              targetPort: 80
            type: LoadBalancer
        wait: yes
